version: '3.8'

services:
  jupyter:
    build: .
    container_name: desarrollo_container
    ports:
      - "8888:8888"
    volumes:
      - ./work:/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /work


